### ISSUE TITLE
Sending credit card numbers directly to the Stripe API is generally unsafe

### ISSUE THREAD

**Issue by H3X0M** [Junaid433/Stripe-CC-Checker#2]
[ ! ] Result : Sending credit card numbers directly to the Stripe API is generally unsafe. To continue processing use Stripe.js, the Stripe mobile bindings, or Stripe Elements. For more information, see https://dashboard.stripe.com/account/integration/settings.                       
[ ! ] Time : 0.483814001083374    

please make new script using stripe

**Comment by Junaid433** [comment]
@H3X0M This is most likely caused by stripe account settings. Try using a different secret key

**Comment by gangstadresta** [comment]
> 
Izts because this is an old stripe method that doesnt work anymore,
